@startuml

class Field {
    -isFilled: boolean
    -index: int

    +setFilled(filled: boolean): void
    +isFilled(): boolean
    +getIndex(): int
}

class Game {
    -turnCounter: int
    -fields: List<Field>
    -player: List<Player>

    +conquer(): void
    +nextTurn(): void
    +finished(): boolean
}

interface IGame {
    +conquer(): void
}

class Player {
    -id: int

    +getId(): int
}

Game .up.> IGame

Game ..> Field : <<uses>>
Game ..> Player : <<uses>>

@enduml